import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import Image from "next/image";
import BG from "./assets/BG.png"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full">
  <body className={`${inter.className} text-white bg-black`}>
    <Navbar />

    {/* Background Image positioned absolutely */}
    <Image
        className="w-full max-h-[3878px] object-cover z-[10] absolute"
        src={BG}
        alt="Background Image"
      />
    {/* Main Content */}

    <div className="relative z-10">
      {children}
    </div>
  </body>
</html>
  );
}
